name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1.1.1
      with:
        go-version: "1.14.3"
    - name: Install magick
      run: |
        set -e
        mkdir -p magickbin
        curl -o magickbin/magick https://imagemagick.org/download/binaries/magick
        chmod +x magickbin/magick
    - name: Run tests
      run: |
        set -e
        chmod +x magickbin/magick
        export PATH=${PWD}/magickbin:${PATH}
        go test ./... -v
    - name: Run tests
      run: |
        set -e
        mkdir -p dist 
        cd cmd/imagefunnel
        go build -o ../../dist/imagefunnel
